image: node:10

pipelines:
  branches:
    master:
      - step:
          name: Install Unicef project dependencies
          caches:
            - node
          script:
            - cd frontend
            - npm install
          artifacts:
            - node_modules/** 
      - step:
          name: Build Unicef project
          script:
            - npm run build
          artifacts:
            - dist/** 