pipelines:
  branches:
    '{master}':
        - step:
            name: Install Unicef project dependencies
            image: zenika/alpine-chrome:with-node
            caches:
              - node
            script:
              - cd frontend
              - npm install
              - npm test
        - step:
            name: Build Unicef project
            script:
              - npm run build
              - set +e
              - npm run lint
              - npm run test:ci
              - set -e
            caches:
              - node
            artifacts:
              - dist/**