name: Running Code Coverage

on: [push, pull_request]

defaults:
  run:
    shell: bash
    working-directory: frontend

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 14.20.1
        uses: actions/setup-node@v3
        with:
          node-version: 14.20.1
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3