name: Frontend Angular Build/Test

on:
  push:
    branches:
      - master

  # the follow line allow this script to be started manually.
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.20.1
        uses: actions/setup-node@v2
        with:
          node-version: 14.20.1

      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Unit test
        run: yarn run ci:test

      - name: Install codecov dependency
        run: npm install -g codecov

      - name: Run Tests
        run: npm run ci:test
      
      - name: Run Codecov Report
        run: codecov

      - name: Build
        run: yarn run ci:build-production
